use employment_styria;
SELECT NUTS3, LAU_CODE, LAU_NAME, REF_DATE,
       (SELECT NON_SELF_EMPL_TOTAL, SELF_EMPL_TOTAL, TEMP_ABSENT_TOTAL, EMPL_TOTAL, LAU_CODE
        FROM   dbo.ERW_ST_BERUF total
		WHERE gemeinde.LAU_CODE = total.LAU_CODE
        FOR XML AUTO, TYPE, ELEMENTS  
       ),
	   (SELECT NON_SELF_EMPL_W, SELF_EMPL_W, TEMP_ABSENT_W, EMPL_TOTAL_W, LAU_CODE
        FROM   dbo.ERW_ST_BERUF women
		WHERE gemeinde.LAU_CODE = women.LAU_CODE
        FOR XML AUTO, TYPE, ELEMENTS  
       ),
	   (SELECT NON_SELF_EMPL_M, SELF_EMPL_M, TEMP_ABSENT_M, EMPL_TOTAL_M, LAU_CODE
        FROM   dbo.ERW_ST_BERUF men
		WHERE gemeinde.LAU_CODE = men.LAU_CODE
        FOR XML AUTO, TYPE, ELEMENTS  
       )
FROM  dbo.ERW_ST_BERUF gemeinde
FOR XML AUTO, TYPE; 